[functions]
  external_node_modules = ["express", "bcrypt", "cors", "jsonwebtoken", "mongoose", "serverless-http"]
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"